# Generated by Django 6.0.3 on 2026-05-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payments_count', models.IntegerField(default=0)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='z_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='z_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.zreport'),
        ),
    ]
