# Generated by Django 6.0.3 on 2026-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_zreport_payment_z_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='zreport',
            name='card_tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='cash_tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='ticket_tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_11_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_11_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_11_net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_21_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_21_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='vat_21_net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
