# Generated by Django 6.0.3 on 2026-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='bill_payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='bill_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='bill_tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='waiter_called',
            field=models.BooleanField(default=False),
        ),
    ]
