# Generated by Django 6.0.3 on 2026-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingredient_stockreceipt_recipeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_recipe',
            field=models.BooleanField(default=True, help_text='Debifează dacă produsul se vinde direct și nu necesită deducere din stoc'),
        ),
    ]
