# Generated by Django 6.0.3 on 2026-04-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_product_requires_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preț achiziție per unitate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.purchaseinvoice'),
        ),
    ]
