# Generated by Django 6.0.3 on 2026-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_purchaseinvoice_stockreceipt_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreceipt',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='unit_price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preț achiziție per unitate fără TVA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='vat_rate',
            field=models.PositiveIntegerField(default=9, help_text='Cota TVA (ex: 9, 11, 19, 21)'),
        ),
    ]
