# Generated by Django 6.0.3 on 2026-05-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_ingredient_alert_threshold_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('fiscal_code', models.CharField(blank=True, help_text='CUI / CIF', max_length=50)),
                ('trade_registry_number', models.CharField(blank=True, help_text='Număr înregistrare Registrul Comerțului', max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='menu.supplier'),
        ),
    ]
