# Generated by Django 6.0.3 on 2026-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_supplier_purchaseinvoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='nir_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
